result
failedWithException: anException
	failedWithException := anException